export const testRoutes =
{
  root: {
    path: "",
    id: "root",
    file: "root.tsx",
  },
  "routes/people.$personId.$planId.remove-plan": {
    file: "routes/people.$personId.$planId.remove-plan.tsx",
    id: "routes/people.$personId.$planId.remove-plan",
    path: ":planId/remove-plan",
    parentId: "routes/people.$personId",
  },
  "routes/chats_.$season.$episode.$slug": {
    file: "routes/chats_.$season.$episode.$slug.tsx",
    id: "routes/chats_.$season.$episode.$slug",
    path: ":slug",
    parentId: "routes/chats_.$season.$episode",
  },
  "routes/admin.episodes.$id.comments": {
    file: "routes/admin.episodes.$id.comments.tsx",
    id: "routes/admin.episodes.$id.comments",
    path: "comments",
    parentId: "routes/admin.episodes.$id",
  },
  "routes/admin.episodes.$id._index": {
    file: "routes/admin.episodes.$id._index.tsx",
    id: "routes/admin.episodes.$id._index",
    path: undefined,
    index: true,
    parentId: "routes/admin.episodes.$id",
  },
  "routes/chats_.$season.$episode": {
    file: "routes/chats_.$season.$episode.tsx",
    id: "routes/chats_.$season.$episode",
    path: "chats/:season/:episode",
    parentId: "root",
  },
  "routes/admin.episodes._index": {
    file: "routes/admin.episodes._index.tsx",
    id: "routes/admin.episodes._index",
    path: "episodes",
    index: true,
    parentId: "routes/admin",
  },
  "routes/admin.episodes.$id": {
    file: "routes/admin.episodes.$id.tsx",
    id: "routes/admin.episodes.$id",
    path: "episodes/:id",
    parentId: "routes/admin",
  },
  "routes/admin.episodes.new": {
    file: "routes/admin.episodes.new.tsx",
    id: "routes/admin.episodes.new",
    path: "episodes/new",
    parentId: "routes/admin",
  },
  "routes/auth._auth.login": {
    file: "routes/auth._auth.login.tsx",
    id: "routes/auth._auth.login",
    path: "login",
    parentId: "routes/auth._auth",
  },
  "routes/people.$personId": {
    file: "routes/people.$personId.tsx",
    id: "routes/people.$personId",
    path: "people/:personId",
    parentId: "root",
  },
  "routes/api.$id[.]json": {
    file: "routes/api.$id[.]json.ts",
    id: "routes/api.$id[.]json",
    path: "api/:id.json",
    parentId: "root",
  },
  "routes/blog.rss[.]xml": {
    file: "routes/blog.rss[.]xml.tsx",
    id: "routes/blog.rss[.]xml",
    path: "blog/rss.xml",
    parentId: "root",
  },
  "routes/($lang).about": {
    file: "routes/($lang).about.tsx",
    id: "routes/($lang).about",
    path: ":lang?/about",
    parentId: "root",
  },
  "routes/(static).home": {
    file: "routes/(static).home.tsx",
    id: "routes/(static).home",
    path: "static?/home",
    parentId: "root",
  },
  "routes/jokes.$jokeId": {
    file: "routes/jokes.$jokeId.tsx",
    id: "routes/jokes.$jokeId",
    path: ":jokeId",
    parentId: "routes/jokes",
  },
  "routes/admin._index": {
    file: "routes/admin._index.tsx",
    id: "routes/admin._index",
    path: undefined,
    index: true,
    parentId: "routes/admin",
  },
  "routes/jokes._index": {
    file: "routes/jokes._index.tsx",
    id: "routes/jokes._index",
    path: undefined,
    index: true,
    parentId: "routes/jokes",
  },
  "routes/posts._index": {
    file: "routes/posts._index.tsx",
    id: "routes/posts._index",
    path: "posts",
    index: true,
    parentId: "root",
  },
  "routes/posts.delete": {
    file: "routes/posts.delete.tsx",
    id: "routes/posts.delete",
    path: "posts/delete",
    parentId: "root",
  },
  "routes/auth._auth": {
    file: "routes/auth._auth.tsx",
    id: "routes/auth._auth",
    path: "auth",
    parentId: "root",
  },
  "routes/posts.$id": {
    file: "routes/posts.$id.tsx",
    id: "routes/posts.$id",
    path: "posts/:id",
    parentId: "root",
  },
  "routes/sign-in.$": {
    file: "routes/sign-in.$.tsx",
    id: "routes/sign-in.$",
    path: "sign-in/*",
    parentId: "root",
  },
  "routes/s.$query": {
    file: "routes/s.$query.tsx",
    id: "routes/s.$query",
    path: "s/:query",
    parentId: "root",
  },
  "routes/credits": {
    file: "routes/credits.tsx",
    id: "routes/credits",
    path: "credits",
    parentId: "root",
  },
  "routes/posts.$": {
    file: "routes/posts.$.tsx",
    id: "routes/posts.$",
    path: "posts/*",
    parentId: "root",
  },
  "routes/admin": {
    file: "routes/admin.tsx",
    id: "routes/admin",
    path: "admin",
    parentId: "root",
  },
  "routes/jokes": {
    file: "routes/jokes.tsx",
    id: "routes/jokes",
    path: "jokes",
    parentId: "root",
  },
  "routes/blog": {
    file: "routes/blog.tsx",
    id: "routes/blog",
    path: "blog",
    parentId: "root",
  },
  "routes/blog._index": {
    file: "routes/blog._index.tsx",
    id: "routes/blog._index",
    path: undefined,
    parentId: "routes/blog",
  },
  "routes/auth.$provider-key": {
    file: "routes/auth.$provider-key.",
    id: "routes/auth.$provider-key",
    path: "auth/:provider-key",
    parentId: "root",
  },
  "routes/($provider-key).about": {
    file: "routes/($provider-key).about.tsx",
    id: "routes/($provider-key).about",
    path: ":provider-key?/about",
    parentId: "root",
  },
  "routes/fruits/route": {
    file: "routes/fruits/route.tsx",
    id: "routes/fruits/route",
    path: "fruits",
    parentId: "root",
  },
  "routes/fruits/index/route": {
    file: "routes/fruits/index/route.tsx",
    id: "routes/fruits/index/route",
    path: "",
    parentId: "routes/fruits/route",
  },
  "routes/fruits/show/route": {
    file: "routes/fruits/show/route.tsx",
    id: "routes/fruits/show/route",
    path: ":id",
    parentId: "routes/fruits/index/route",
  },
  catchall: {
    path: "/somewhere/cool/*",
    index: undefined,
    caseSensitive: undefined,
    id: "catchall",
    parentId: "root",
    file: "catchall.tsx",
  },
};
